### ISSUE TITLE
[K4] 4.0 Compatibility

### ISSUE THREAD

**Issue by afbora** [steirico/kirby-plugin-custom-add-fields#68]
The plugin doesn't work correctly in K4

Kirby 4.0.0-rc.4
PHP 8.1.23

**Comment by josephtatum** [comment]
Just here to second this. Seeing what appears to be a vue.js error in the console when visiting `localhost:8000/panel` using Kirby 4.0.0 and PHP 8.2.11. Nothing renders in the DOM when visiting the panel and the issue is resolved when I remove the plugin.

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'props')
    at vue.min.js:11:38580
    at yr (vue.min.js:11:38751)
    at yr (vue.min.js:11:39066)
    at Sr.t.extend (vue.min.js:11:40398)
    at R.forEach.t.<computed> [as component] (vue.min.js:11:47715)
    at index.js?1688112899:258:13
    at Array.forEach (<anonymous>)
    at panel.plugin.use (index.js?1688112899:251:35)
    at t.use (vue.min.js:11:47468)
    at index.min.js:1:384429
```

**Comment by carstengrimm** [comment]
+1, wish this was compatible.

**Comment by steirico** [comment]
As you probably know, [Kirby 4 provides certain functions of the plugin](https://getkirby.com/docs/reference/panel/blueprints/page#page-creation-dialog). The question therefore arises whether the plugin is still needed and should be further maintained.

With the following poll I would like to find out which features of the plugin are really needed:
https://forum.getkirby.com/t/futur-of-the-custom-add-fields-plugin/30500

Depending on the result, I will decide whether the plugin will be continued or not. In any case, I am willing to contribute missing features to Kirby.

**Comment by carstengrimm** [comment]
for me the plugin became obsolete. Just randomly trying to make it work with said build in functions. My attempt was to simply have a preview picture when certain templates are selected (for building a one pager with different sections where as a page equals to different sections)

![image](https://github.com/steirico/kirby-plugin-custom-add-fields/assets/5014509/2af0d28d-c74d-413f-bb25-f61c4552e9d6)

this is possible with core functions within the blueprints e.g.:

```
title: One-Pager-Child Advantages
create:
  fields:
    - info

sections:
  content:
    type: fields
    fields:
      info:
        type: info
        text: | 
          <img src="https://placehold.co/600x400">
```

So within the blueprints we add the create function, telling there is a "info" field, and the info field includes the url / html to the picture.
